### ISSUE TITLE
Add schedule that supports loops

### ISSUE THREAD

**Issue by svenschneider** [rosym-project/algorithm-dsl#11]

**Comment by minhnh** [comment]
@svenschneider  is this resolved with 1dabfd2?

**Comment by svenschneider** [comment]
Yes, together with commits e97c0892365699ca19f17f54ee97e7d53a91dfe4 and 911608f92ed3d27354ae5d7bcb2eafd9e4fa7963 this is indeed resolving this issue. Closing.
